### PR TITLE
[issue#88] -- Fix for elli_http:chunk_loop/1

### PR DESCRIPTION
**Pull request by zampino**
- correct message matching in elli_http:chunk_loop/1 receive block
- basic unit test

## Note:

I had to struggle a bit to learn a bit of eunit,
so `tests/elli_http_tests.erl` doesn't really follow your conventions, sorry.....

I'll be glad to react on suggestions, how to make it more sound.

Cheers,
A

### CODE REVIEW

**Comment by knutin** [comment]
It looks good. Your test makes sure chunk loop handles that exact message correctly. It would maybe be also very interesting to see what happens we have a chunk loop open and then the client closes the connection. That would prove that the code works correctly within the context it runs.

**Comment by zampino** [comment]
Yes I agree, for instance in a variant of the [chunked test](https://github.com/knutin/elli/blob/master/test/elli_tests.erl#L209).

but I wouldn't know how to simulate "client-closes-connection" through a `httpc:request`

**Comment by knutin** [comment]
Good point. If you're up for some hacking, it would be possible to write a very simple http client that would close the connection prematurely. It would open a socket, send some headers, see `start_slow_client/2` in `elli_tests` for an example.

I'm also happy to accept the patch as is. You already fixed the problem. :-)

**Comment by zampino** [comment]
Ok, if you agree, you could merge the patch, and then if time permits I can try to improve the test suite.
Thanks for the feedback, :cool:

**Pull request merged**
